FROM node:20-alpine
RUN npm install -g pnpm
RUN pnpm --version
WORKDIR /user/src/app

COPY ./packages ./packages
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml
COPY ./package.json ./package.json

COPY ./turbo.json ./turbo.json

COPY ./apps/http ./apps/http

RUN pnpm install

EXPOSE 9000

CMD npm run db:push && npm run db:generate && npm run start:http


